name: pyright

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: pyright
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run: git submodule update --init --recursive
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: pip
      run: pip install aiohttp aiohttp-session types-requests asyncpg sqlalchemy datrie pyright
    - name: pyright
      run: pyright
